config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static#home'
  get 'r/:username' => 'static#home', as: :user_landing
  
  
  devise_for :accounts, :skip => [:registration]
  as :account do
    
    get 'register/:plan/:username' => 'registrations#new', as: :new_account_registration
    #get ':username/register' => 'registrations#new', as: :registration
    post 'register' => 'registrations#create', as: :account_registration
    get 'accounts/edit' => 'registrations#edit', as: :edit_account_registration
    patch 'accounts' => 'accounts/registrations#update', as: :edit_account_registration_patch
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  authenticate(:account) do
    get 'dashboard' => 'dashboard#index', as: :dashboard
    get 'accounts/credit_card' => 'account#credit_card', as: :account_credit_card
    post 'accounts/credit_card' => 'account#process_credit_card', as: :process_credit_card
  end
  
  # Static pages
  get 'terms_conditions' => 'static#terms_conditions', as: :terms_conditions
  
end

app/models/account.rb
require 'digest/md5'

class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :trackable

  belongs_to :plan
  belongs_to :refer, :class_name => 'Account'

  validates :username, presence: true
  validates :username, length: { in: 3..20 }
  validates :username, uniqueness: { case_sensitive: false }
  validates :username, format: { with: /\A[[:alnum:]]+\z/ }
  
  
  def avatar
    'http://www.gravatar.com/avatar/' + Digest::MD5.hexdigest(self.email.downcase) + '?s=35'
  end
end
 

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/controllers/account_controller.rb
class AccountController < ApplicationController

  def credit_card
    
  end

  def process_credit_card
    
    charge = Stripe::Charge.create(
      :amount => current_account.plan.price.to_i * 100,
      :currency => "usd",
      :card => params[:stripe_token],
      :description => "Plan #{current_account.plan.name} ($#{current_account.plan.price})"
    )

    current_account.update(stripe_charge: charge.id) if charge.paid

    flash[:breaking_alert] = nil
    redirect_to dashboard_path, notice: 'Tu pago fue procesado con éxito. Bienvenido a Lanzamiento Global!'

    rescue Stripe::CardError => e
      redirect_to account_credit_card_path, error: e.message

    rescue Stripe::StripeError => e
      redirect_to account_credit_card_path, error: e.message
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  before_filter :set_username, unless: :account_signed_in?

  rescue_from Exceptions::NotFound, with: :not_found


  def after_sign_in_path_for(resource)
    admin_user_signed_in? ? admin_dashboard_path : dashboard_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :current_password, :firstname, :lastname, :phone, :address, :refer_id, :plan_id)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :current_password, :firstname, :lastname, :phone, :address, :refer_id, :plan_id)
    end
  end
  
  def set_username
    @username = params[:username] || Account.all.first.username
  end

  def check_payment
    redirect_to account_credit_card_path if account_signed_in? and current_account.stripe_charge.blank?
  end

  private
    def not_found
      render template: 'errors/not_found', status: 404
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

   before_filter :check_payment

  def index
    @children = Account.where(refer: current_account)
    
    @parent = Account.find(current_account.refer.id) if current_account.refer.present?
    @parent2 = Account.find(@parent.refer.id) if @parent.present? and @parent.refer.present?
    @parent3 = Account.find(@parent2.refer.id) if @parent2.present? and @parent2.refer.present?
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    refer = Account.find_by(username: params[:username])
    refer = Account.all.first unless refer.present? # In case of a kind of hack

    plan = Plan.where(name: params[:plan]).first
    plan = Plan.all.first unless plan.present? # In case of a kind of hack

    build_resource({plan_id: plan.id, refer_id: refer.id})
    respond_with self.resource, layout: 'home'
  end

  def create
    build_resource(sign_up_params)

    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      #respond_with resource, 
      render 'devise/registrations/new', layout: 'home'
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home
  	if @username.present? 

      account = Account.find_by(username: params[:username])

  		raise Exceptions::NotFound if account.present? and account.stripe_charge.blank?
  	end

    render layout: 'home'
  end

  def terms_conditions
    render layout: 'home'
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dashboard/index.html.erb
<div class="innerAll border-top">
  
  <!-- row -->
  <div class="row">

    <div class="col-md-9">
      <div class="widget">

        <!-- Category Heading -->
        <div class="widget-head">
          <h4 class="margin-none">Mis antecesores</h4>
          <div class="clearfix"></div>
        </div>
        <!-- End Category Heading -->
        
        <!-- Category Listing -->
        <% if @parent.present? %>
          <div class="bg-gray-hover overflow-hidden">
            <div class="row innerAll half  border-bottom">
              <div class="media">
                <a href="" class="pull-left"><img src="<%= @parent.avatar %>" alt="" class="img-circle" ></a>
                <div class="media-body">
                    <%= @parent.username %>
                </div>
                <div class="clearfix"></div>

              </div>
            </div>
          </div>
        <% end %>
        
        <% if @parent2.present? %>
          <div class="bg-gray-hover overflow-hidden">
            <div class="row innerAll half  border-bottom">
              <div class="media">
                <a href="" class="pull-left"><img src="<%= @parent2.avatar %>" alt="" class="img-circle" ></a>
                <div class="media-body">
                  <%= @parent2.username if @parent2.present? %>
                </div>
                <div class="clearfix"></div>

              </div>
            </div>
          </div>
        <% end %>
        
        <% if @parent3.present? %>
          <div class="bg-gray-hover overflow-hidden">
            <div class="row innerAll half  border-bottom">
              <div class="media">
                <a href="" class="pull-left"><img src="<%= @parent3.avatar %>" alt="" class="img-circle" ></a>
                <div class="media-body">
                  <%= @parent3.username if @parent3.present? %>
                </div>
                <div class="clearfix"></div>

              </div>
            </div>
          </div>
        <% end %>


      </div>
      <div class="widget">

        <div class="widget-head">
          <h4 class="margin-none">Mis referidos</h4>
          <div class="clearfix"></div>
        </div>

        <% @children.each do |x| %>
          <div class="bg-gray-hover overflow-hidden">
            <div class="row innerAll half  border-bottom">
              <div class="media">
                <a href="" class="pull-left"><img src="<%= x.avatar %>" alt="" class="img-circle" ></a>
                <div class="media-body">
                  <%= x.username %>
                </div>
                <div class="clearfix"></div>

              </div>
            </div>
          </div>
        <% end %>

      </div>
      <!-- // END col-separator --> 
    </div>
    <!-- // END col -->

    <!-- col -->
    <div class="col-md-3">
      <!-- 
      <div class="widget">

        <div class="widget-head">
            <h4 class="margin-bottom-none">Referidos recientes</h4>
        </div>
        <div class="border-bottom bg-gray-hover innerAll half">
          <i class="fa fa-clock-o text-muted fa-fw"></i>
          <a href="" class="">John</a>
          <small class="text-muted-dark">on 16 Jan 2014</small>
        </div>

      </div>
    </div>
     -->
  </div>
  <!-- // END row -->

</div>

</div>
<!-- // Content END -->

<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lanzamientoglobal</title>
  <%= stylesheet_link_tag  'theme', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Main Container Fluid -->
  <div class="container-fluid menu-hidden">
        
    <!-- Content -->
    <div id="content">

      <div class="navbar hidden-print main navbar-default" role="navigation">
  <div class="user-action user-action-btn-navbar pull-right">
    <button class="btn btn-sm btn-navbar btn-inverse btn-stroke hidden-lg hidden-md"><i class="fa fa-bars fa-2x"></i></button>
  </div>
  <%= link_to raw('<span class="hidden-xs hidden-sm inline-block"><span>Lanzamiento</span>Global</span>'), dashboard_path, :class => 'logo' %>
  
  <% if account_signed_in? %>
    <ul class="main pull-right">
      <li class="hidden-xs hidden-sm">Mi enlace de afiliado: <input type="text" value="<%= user_landing_url(current_account.username) %>" class="my-refer-url" /> </li>
      <li class="hidden-xs">Usuarios referidos:  <strong class="text-primary">24</strong></li>
      <li class="dropdown username hidden-xs ">
        <a href="" class="dropdown-toggle" data-toggle="dropdown"><img src="<%= current_account.avatar %>" class="img-circle" alt="Profile" /> <%= current_account.firstname %> <span class="caret"></span></a>

        <ul class="dropdown-menu pull-right">
          <li><%= link_to raw("<i></i> Mi Cuenta"), edit_account_registration_path, :class => 'glyphicons user' %></li>
          <li><%= link_to raw("<i></i> Salir"), destroy_account_session_path, method: :delete, :class => 'glyphicons lock' %></li>
        </ul>
      </li>
    </ul> 
  <% end %>
</div>
<!-- // END navbar -->

  <%= yield %>
  
      <div id="footer" class="hidden-print">
      
      <!--  Copyright Line -->
      <div class="copy">&copy; 2014 - LanzamientoGlobal</div>
      <!--  End Copyright Line -->
  
    </div>
    
    <!-- // Footer END -->
    
  </div>
  <!-- // Main Container Fluid END -->
  

  <!-- Global -->
  <script data-id="App.Config">
      var App = {};        var basePath = '',
          commonPath = '../assets/',
          rootPath = '../',
          DEV = false,
          componentsPath = '../assets/components/';

      var primaryColor = '#c72a25',
          dangerColor = '#b55151',
          successColor = '#609450',
          infoColor = '#4a8bc2',
          warningColor = '#ab7a4b',
          inverseColor = '#45484d';

      var themerPrimaryColor = primaryColor;

  </script>



</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>

<html dir="ltr" lang="es-ES">
<head>
  <meta charset="UTF-8">

  <title>Lanzamiento Global</title>
  <meta content="noodp, noydir" name="robots">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" media="all" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,300,700" media="all" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" media="all" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Bitter:400,700" media="all" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Raleway:400,600,800" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Oswald:300,400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "home", media: "all" %>
  <!--[if gte IE 9]>
    <style type="text/css">
      .gradient {
         filter: none;
      }
    </style>
  <![endif]-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body class="landing-med template-custom">
  <div id="med-top-filler">
    <div class="container">
      <ul class="pull-right top-nav nav nav-pills">
        <li><a href="#">Cont&aacute;ctanos</a></li>
        <% if account_signed_in? %>
        <li><%= link_to "Mi Cuenta", dashboard_path %></li>
          <li><%= link_to "Salir", destroy_account_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Ingresar", new_account_session_path %></li>
        <% end %>
      </ul>      
    </div>
  </div>
  <div id="med-navbar">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <%= link_to 'Lanzamiento Global', root_path, :class => 'med-brand' %>
        </div>
        <div class="col-sm-8">
          <h4 id="descuento-valido-hasta">Esta oferta estar&aacute; disponible hasta la media noche de hoy</h4>
          <div class="countdown">
            <div id="midnight-countdown"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <%= yield %>
  <%= javascript_include_tag "application" %>
</body>
</html>